routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::group(['prefix' => 'admin', 'middleware' => ['role:admin']], function () {

    Route::group(['namespace' => 'Admin'], function () {
        Route::get('/', 'DashboardController@dashboard')->name('admin.index');
    });

    Route::group(['namespace' => 'Core'], function () {
        Route::resource('categories', 'CategoryController');
        Route::resource('tags', 'TagController');
        Route::resource('articles', 'ArticleController');

        Route::post('/comments/{article}', [
            'as' => 'comments.store',
            'uses' => 'CommentController@store'
        ]);
        Route::resource('comments', 'CommentController')->except([
            'store'
        ]);

        Route::get('/vote/{vote}/article/{article}', 'VoteController@article');
        Route::get('/vote/{vote}/comment/{comment}', 'VoteController@comment');
    });

});

app/Models/Article.php
<?php

namespace App\Models;

use App\User;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Str;

class Article extends Model
{
    protected $fillable = [
        'title',
        'content',
        'published',
        'published_at'
    ];

    public function author()
    {
        return $this->belongsTo(User::class, 'user_id');
    }

    public function categories()
    {
        return $this->belongsToMany(Category::class);
    }

    public function tags()
    {
        return $this->belongsToMany(Tag::class);
    }

    public function rubrics()
    {
        return $this->belongsToMany(Rubric::class);
    }

    public function comments()
    {
        return $this->hasMany(Comment::class);
    }

    public function votes()
    {
        return $this->morphMany(Vote::class, 'voteable');
    }

    public function setPublishedAttribute($value)
    {
        $this->attributes['published'] = (bool)$value;
    }

    public function getWithAllData()
    {
        return $this->with(['author', 'categories', 'tags', 'rubrics']);
    }
}

app/Http/Controllers/Core/ArticleController.php
<?php

namespace App\Http\Controllers\Core;

use App\Models\{Article, Category, Rubric, Tag, Vote};
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class ArticleController extends Controller
{
    protected $article;
    protected $tag;
    protected $category;
    protected $rubrics;

    public function __construct(Article $article, Tag $tag, Category $category, Rubric $rubrics)
    {
        $this->article = $article;
        $this->category = $category;
        $this->tag = $tag;
        $this->rubrics = $rubrics;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('admin.articles.index', [
            'articles' => $this->article->getWithAllData()->paginate(10),
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.articles.create', [
            'article'   => [],
            'categories' => $this->category->get(),
            'rubrics' => $this->rubrics->get()
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $article = $request->user()->articles()->create($request->all());
        $article->categories()->attach($request->categories);
        $article->rubrics()->attach($request->rubrics);
        $article->tags()->attach(Tag::syncTags($request->tags));
        return redirect()->route('articles.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Article $article
     * @return \Illuminate\Http\Response
     */
    public function show(Article $article)
    {
        return view('admin.articles.show', [
            'article' => $article->getWithAllData()->where('id', $article->id)->first()
        ]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Article  $article
     * @return \Illuminate\Http\Response
     */
    public function edit(Article $article)
    {
        return view('admin.articles.edit', [
            'article'   => $article->getWithAllData()->where('id', $article->id)->first(),
            'categories' => $this->category->get(),
            'rubrics' => $this->rubrics->get()
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  \App\Models\Article $article
     * @return \Illuminate\Http\RedirectResponse
     */
    public function update(Request $request, Article $article)
    {
        $article->update($request->all());
        $article->categories()->sync($request->categories);
        $article->rubrics()->sync($request->rubrics);
        $article->tags()->sync(Tag::syncTags($request->tags));

        return redirect()->route('articles.show', $article);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Article $article
     * @return \Illuminate\Http\Response
     * @throws \Exception
     */
    public function destroy(Article $article)
    {
        $article->delete();
        return redirect()->route('articles.index');
    }
}

resources/views/admin/articles/create.blade.php
@extends('admin.layouts.app')

@push('styles')
    <link href="{{ asset('css/chosen.min.css') }}" rel="stylesheet">
    <link href="{{ asset('css/bootstrap-tagsinput.css') }}" rel="stylesheet">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.13.1/styles/default.min.css" rel="stylesheet">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/quill/1.3.6/quill.snow.css" rel="stylesheet">
@endpush

@push('scripts')
    <script type="text/javascript" src="{{ asset('js/chosen.jquery.min.js') }}"></script>
    <script type="text/javascript" src="{{ asset('js/bootstrap-tagsinput.js') }}"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.13.1/highlight.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/quill/1.3.6/quill.min.js"></script>
    <script type="text/javascript" src="{{ asset('js/create-article.js') }}"></script>
@endpush

@section('content')
    <div class="main-content-container container-fluid px-4">
        <!-- Page Header -->
        <div class="page-header row no-gutters py-4">
            <div class="col-12 col-sm-4 text-center text-sm-left mb-0">
                <h3 class="page-title">Добавить статью</h3>
            </div>
        </div>
        <form id="create" method="POST" action="{{route('articles.store')}}">
            @csrf
            <div class="row">
                <div class="col-lg-9 col-md-12">
                    <div class="card card-small mb-3">
                        <div class="card-body">
                            <div class="add-new-post">
                                <select name="categories[]" data-placeholder="Категории" class="chosen-select form-control form-control-lg mb-3" multiple>
                                    @foreach ($categories as $category)
                                        <option value="{{$category->id}}">{{$category->title}}</option>
                                    @endforeach
                                </select>
                                <input name="title" class="form-control form-control-lg mb-3" type="text" placeholder="Заголовок">
                                <input name="content" type="hidden">
                                <div id="editor-container" class="add-new-post__editor mb-1"></div>
                                <input name="tags" class="form-control form-control-lg mb-3" type="text" data-role="tagsinput" placeholder="Теги">
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-3 col-md-12">
                    <div class='card card-small mb-3'>
                        <div class="card-header border-bottom">
                            <h6 class="m-0">Действия</h6>
                        </div>
                        <div class='card-body p-0'>
                            <ul class="list-group list-group-flush">
                                <li class="list-group-item p-3">
                                    <div class="custom-control custom-radio mb-1">
                                        <input
                                                name="published"
                                                type="radio"
                                                class="custom-control-input"
                                                id="published"
                                                value="1"
                                        >
                                        <label class="custom-control-label" for="published">Опубликовано</label>
                                    </div>
                                    <div class="custom-control custom-radio mb-1">
                                        <input
                                                name="published"
                                                type="radio"
                                                class="custom-control-input"
                                                id="draft"
                                                value="0"
                                        >
                                        <label class="custom-control-label" for="draft">Черновик</label>
                                    </div>
                                </li>
                            </ul>
                        </div>
                        <div class="card-header border-bottom">
                            <h6 class="m-0">Рубрики</h6>
                        </div>
                        <div class='card-body p-0'>
                            <ul class="list-group list-group-flush">
                                <li class="list-group-item px-3 pb-2">
                                    @foreach($rubrics as $rubric)
                                        <div class="custom-control custom-checkbox mb-1">
                                            <input name="rubrics[]" type="checkbox" value="{{$rubric->id}}" class="rubrics custom-control-input" id="category{{$rubric->id}}">
                                            <label class="custom-control-label" for="category{{$rubric->id}}">{{$rubric->title}}</label>
                                        </div>
                                    @endforeach
                                </li>
                                <li class="list-group-item d-flex px-3 justify-content-center">
                                    <button type="submit" class="btn btn-sm btn-outline-accent"><i class="material-icons">save</i> Сохранить</button>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </form>
@endsection

resources/views/admin/articles/edit.blade.php
@extends('admin.layouts.app')

@push('styles')
    <link href="{{ asset('css/chosen.min.css') }}" rel="stylesheet">
    <link href="{{ asset('css/bootstrap-tagsinput.css') }}" rel="stylesheet">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.13.1/styles/default.min.css" rel="stylesheet">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/quill/1.3.6/quill.snow.css" rel="stylesheet">
@endpush

@push('scripts')
    <script type="text/javascript" src="{{ asset('js/chosen.jquery.min.js') }}"></script>
    <script type="text/javascript" src="{{ asset('js/bootstrap-tagsinput.js') }}"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.13.1/highlight.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/quill/1.3.6/quill.min.js"></script>
    <script type="text/javascript" src="{{ asset('js/edit-article.js') }}"></script>
@endpush

@section('content')
    <div class="main-content-container container-fluid px-4">
        <!-- Page Header -->
        <div class="page-header row no-gutters py-4">
            <div class="col-12 col-sm-4 text-center text-sm-left mb-0">
                <h3 class="page-title">Редактировать статью</h3>
            </div>
        </div>
        <form id="create" method="POST" action="{{route('articles.update', $article)}}">
            <input name="_method" type="hidden" value="PUT">
            @csrf
            <div class="row">
                <div class="col-lg-9 col-md-12">
                    <div class="card card-small mb-3">
                        <div class="card-body">
                            <div class="add-new-post">
                                <select name="categories[]" data-placeholder="Категории" class="chosen-select form-control form-control-lg mb-3" multiple>
                                    @foreach ($categories as $category)
                                        <option value="{{$category->id}}" @if($article->categories->contains($category)) selected @endif>
                                            {{$category->title}}
                                        </option>
                                    @endforeach
                                </select>
                                <input name="title" class="form-control form-control-lg mb-3" type="text" value="{{$article->title}}">
                                <input name="content" type="hidden" value="{{$article->content}}">
                                <div id="editor-container" class="add-new-post__editor mb-1"></div>
                                <input
                                        name="tags"
                                        class="form-control form-control-lg mb-3"
                                        type="text"
                                        data-role="tagsinput"
                                        value="@foreach($article->tags as $tag) {{$tag->title}} @if (!$loop->last),@endif @endforeach">
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-3 col-md-12">
                    <div class='card card-small mb-3'>
                        <div class="card-header border-bottom">
                            <h6 class="m-0">Действия</h6>
                        </div>
                        <div class='card-body p-0'>
                            <ul class="list-group list-group-flush">
                                <li class="list-group-item p-3">
                                    <div class="custom-control custom-radio mb-1">
                                        <input
                                                name="published"
                                                type="radio"
                                                class="custom-control-input"
                                                id="published"
                                                value="1"
                                                @if($article->published) checked @endif
                                        >
                                        <label class="custom-control-label" for="published">Опубликовано</label>
                                    </div>
                                    <div class="custom-control custom-radio mb-1">
                                        <input
                                                name="published"
                                                type="radio"
                                                class="custom-control-input"
                                                id="draft"
                                                value="0"
                                                @if(!$article->published) checked @endif
                                        >
                                        <label class="custom-control-label" for="draft">Черновик</label>
                                    </div>
                                </li>
                            </ul>
                        </div>
                        <div class="card-header border-bottom">
                            <h6 class="m-0">Рубрики</h6>
                        </div>
                        <div class='card-body p-0'>
                            <ul class="list-group list-group-flush">
                                <li class="list-group-item px-3 pb-2">
                                    @foreach($rubrics as $rubric)
                                        <div class="custom-control custom-checkbox mb-1">
                                            <input name="rubrics[]" type="checkbox" value="{{$rubric->id}}" @if($article->rubrics->contains($rubric)) checked @endif class="rubrics custom-control-input" id="category{{$rubric->id}}">
                                            <label class="custom-control-label" for="category{{$rubric->id}}">{{$rubric->title}}</label>
                                        </div>
                                    @endforeach
                                </li>
                                <li class="list-group-item d-flex px-3 justify-content-center">
                                    <button type="submit" class="btn btn-sm btn-outline-accent"><i class="material-icons">save</i> Сохранить</button>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
    </div>
    </form>
@endsection

resources/views/admin/articles/index.blade.php
@extends('admin.layouts.app')

@push('styles')
    <link href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.13.1/styles/default.min.css" rel="stylesheet">
@endpush

@push('scripts')
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.13.1/highlight.min.js"></script>
@endpush

@section('content')
    <div class="container">
        @forelse($articles as $article)
            <article class="card">
                <header class="card-header">
                    <p>{{$article->author->name}} {{$article->published_at}}</p>
                    <h2><a href="{{route('articles.show', $article)}}">{{$article->title}}</a></h2>
                    <p>
                        @foreach($article->categories as $category)
                            <span>{{$category->title}} @if (!$loop->last),@endif </span>
                        @endforeach
                    </p>
                </header>
                <main class="card-body">
                    {!! \Illuminate\Support\Str::words($article->content, 25, '...')  !!}
                </main>
                <footer class="card-footer">
                    @forelse($article->tags as $tag)
                        <span>{{$tag->title}}, </span>
                    @empty
                        <span>Nothing</span>
                    @endforelse
                </footer>
            </article>
        @empty
            <h2>Nothing</h2>
        @endforelse
        <ul class="pagination">
            {{$articles->links()}}
        </ul>
    </div>
@endsection

resources/views/admin/articles/show.blade.php
@extends('admin.layouts.app')

@section('content')
    <div class="container">
        @if (isset($errors) && count($errors))

            There were {{count($errors->all())}} Error(s)
            <ul>
                @foreach($errors->all() as $error)
                    <li>{{ $error }} </li>
                @endforeach
            </ul>

        @endif
        @include('admin.comments.create')
    </div>
@endsection