routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::group(['prefix' => 'admin', 'middleware' => ['role:admin']], function () {

    Route::group(['namespace' => 'Admin'], function () {
        Route::get('/', 'DashboardController@dashboard')->name('admin.index');
    });

    Route::group(['namespace' => 'Core'], function () {
        Route::resource('categories', 'CategoryController');
        Route::resource('tags', 'TagController');
        Route::resource('articles', 'ArticleController');

        Route::post('/comments/{article}', [
            'as' => 'comments.store',
            'uses' => 'CommentController@store'
        ]);
        Route::resource('comments', 'CommentController')->except([
            'store'
        ]);

        Route::get('/vote/{vote}/article/{article}', 'VoteController@article');
        Route::get('/vote/{vote}/comment/{comment}', 'VoteController@comment');
    });

});

app/Models/Tag.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Tag extends Model
{
    protected $fillable = ['title'];

    public static function syncTags($tags)
    {
        $ids = [];
        $tags = explode(',', $tags);

        foreach ($tags as $tagTitle) {
            $tag = Tag::whereTitle($tagTitle)->first();

            if(is_null($tag)) {
                $tag = Tag::create(['title' => $tagTitle]);
            }
            array_push($ids, $tag->id);
        }

        return $ids;
    }
}

app/Http/Controllers/Core/TagController.php
<?php

namespace App\Http\Controllers\Core;

use App\Models\Tag;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class TagController extends Controller
{
    protected $tag;

    public function __construct(Tag $tag)
    {
        $this->tag = $tag;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('admin.tags.index', [
            'tags' => $this->tag->paginate(10),
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.tags.create', [
            'tag'   => []
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->tag->create($request->all());
        return redirect()->route('tags.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Tag $tag
     * @return void
     */
    public function show(Tag $tag)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Tag  $tag
     * @return \Illuminate\Http\Response
     */
    public function edit(Tag $tag)
    {
        return view('admin.tags.edit', [
            'tag'   => $tag
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Tag  $tag
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Tag $tag)
    {
        $tag->update($request->all());
        return redirect()->route('tags.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Tag $tag
     * @return \Illuminate\Http\Response
     * @throws \Exception
     */
    public function destroy(Tag $tag)
    {
        $tag->delete();
        return redirect()->route('tags.index');
    }
}

resources/views/admin/tags/create.blade.php
@extends('admin.layouts.main_app')

@section('content')
    <div class="container">
        <form class="form-row" action="{{route('tags.store')}}" method="post">
            {{ csrf_field() }}

            @include('admin.tags.partials.form')
        </form>
    </div>
@endsection

resources/views/admin/tags/edit.blade.php
@extends('admin.layouts.main_app')

@section('content')
    <div class="container">
        <form class="form-row" action="{{route('tags.update', $tag)}}" method="post">
            <input type="hidden" name="_method" value="put">
            {{ csrf_field() }}

            @include('admin.tags.partials.form')
        </form>
    </div>
@endsection

resources/views/admin/tags/index.blade.php
@extends('admin.layouts.main_app')

@section('content')
    <div class="container">
        <div class="row">
            <h1>Tags</h1>
        </div>
        <div class="row">
            <a href="{{route('tags.create')}}">Create</a>
        </div>
        <div class="row">
            <table class="table table-striped">
                <thead>
                <th>Наименование</th>
                <th>Публикация</th>
                <th>Действие</th>
                </thead>
                <tbody>
                @forelse($tags as $tag)
                    <tr>
                        <td>{{$tag->name}}</td>
                        <td>{{$tag->published}}</td>
                        <td>
                            <a href="{{route('tags.edit', $tag)}}">Edit</a>
                            <form action="{{route('tags.destroy', $tag)}}" method="post">
                                <input type="hidden" name="_method" value="delete">
                                {{ csrf_field() }}
                                <button type="submit">delete</button>
                            </form>
                        </td>
                    </tr>
                @empty
                    <tr>
                        <td colspan="4" class="text-center"><h2>Nothing</h2></td>
                    </tr>
                @endforelse
                </tbody>
                <tfoot>
                <tr>
                    <td colspan="4">
                        <ul class="pagination">
                            {{$tags->links()}}
                        </ul>
                    </td>
                </tr>
                </tfoot>
            </table>
        </div>
    </div>
@endsection